# Parameters for the Parallel API Requester
# Ensure the appropriate values  are configured to avoid API request or token request rejections due to limit overreaches.
provider: azure
model_name: gpt-35-turbo
max_tokens: 20
temperature: 0.7
request_rate_limit: 100
token_rate_limit: 20000
return_in_json_format: True
cost_print_interval: 100 # print cost every k requests are completed
budget: 15 # in dollars
    